dist: focal

language: python

python:
  - pypy3

git:
  depth: 1
  quiet: true

env:
  global:
    - secure: pJ5UhxwkiBZgk/PAG/DXdZeXdcXfCBAKJK13hKG+DNSFYPEnNZ7tNKuJ47cBYhFzCAFL3qdlVi9Pn56AqzXjBCmRisxUM0RI+seGCedZn/d6JbhR/QXi22EEojQ2MzELt3njo75ihzzWb1VLoZvAmVwJ/E1OEHZuyfJqBixPi3YFcrBC4IBX3PF6pZKQDTgBxRyH1ApmBM1D9ctcOZ8XqZYL4P9/bljWFD5SP5K5UfyRtsQjJATScuWvljbc10OW5f5boFvEu9SjkaEUEubLEypkPGBrtscacJRJWKlQzR0PqvgKtlVDNb4sksPOPQVX9cmwFMyg39Gi5JrD1O+yEA1a2AfUF8rmgIc7Xb8b/9OVZuDsiDX0JBTESCId0FWLrbK63pkJYhK5uEbADw1561mQEzLUVu4IsUJsqE6giDeJ8y52Oh1pcQH6fTS2Omt6NIBGuSX+Wxh+MrQ4dNvCKt0rVDAI7PslSNNSihEjF0ra4oIgWn19i2wyr8taq6Wvi7YATUjXIpLaXjBJGWsrOMSNufemCYNG/BHNmE8m7JJsCSmG1Jn9atF4lx7A5PXDW3A1czYa9vCv0AgxgmTznUM0/5YuK3IVoWoWhAeRlxLj/fYKgxO4fdaUKIyf84Vcr+QhyYBEScoIfVNt9YbyLQ9V/EOu71OdtKBtj6+o4NA=
    - PORTAGE_ROOT="$(mktemp --directory)"
    - PORTAGE_VERSION="$(.travis-scripts/get_latest_portage_version)"
    - PORTAGE_CONFIGROOT="${PORTAGE_ROOT}"
    - PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"

install:
  - .travis-scripts/install_portage
  - .travis-scripts/setup_portage
  - .travis-scripts/add_required_user_and_group

before_script:
  - pip install PyYAML

script:
  - repoman full --include-dev

notifications:
  email:
    on_failure: change
