dist: bionic

language: python

python:
  - pypy3

git:
  depth: 1
  quiet: true

env:
  global:
    - secure: NGfoIBZGZj1SBQBhfukXGpV8DJKlbMBsT3pq7dS2TJIp+GzLljAtlARxlN4Y/1QqYvHipBlzQdlvQLgUudIz1ZF0Isn0Orj+jyvFfC1eSeO4wu8KcetW9PqkQdj2HwUQW9lM+Bhi4dl0iY6/j/xgiFoy/CpXLFcwaqgPzIzntRY9HMHlKJvCoHfuOr9YpCU4j+WGLR3lPKdjrDyvjTYc1qXEZHc/uh7SkGTthLrlBSjcV3riakdqQleGSfQw33rd+ymULrUEMa8PHp2HbXSZtYBo88JDMpp8dE4T7PKeKJRQE78awsRhXENEi898COsQ72nnBoBtHn7Y8d6nqr3j1gSGcmjfW/ZhRxRC2BDKsGY0QcrjuoAGzhWuYjvoyFbWZmMajDtzFqv0yRsW6S8sonL9cH13/hjzgIhd0DzvEwH/U+mp61KXNMA/cps7CruEmNGDjc/p4DJ6GfRWTKgL6f6Y7+pp0BKQk7DQjx5DJ5xahnWP2Pql2oHqpG5Q+MhGdyVpBZlfp8yc2xn9Vt80r2uQ069Nt1uWcS8Rtr1ZUbJmMbkZ36jwBp0YNURXYHYXwnMCvH/gQ0BrTq5RPuPYMe04U+vjB1mBhUKaiz7puRYIOU6k/Cul05PkjYXY9yaHAuK+0DqBDNGzetsAXqPF3x8bqx+0TTxxGQn6h6FZpTU=
    - PORTAGE_ROOT="$(mktemp --directory)"
    - PORTAGE_VERSION="$(.travis-scripts/get_latest_portage_version)"
    - PORTAGE_CONFIGROOT="${PORTAGE_ROOT}"
    - PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"

install:
  - .travis-scripts/install_portage
  - .travis-scripts/setup_portage
  - .travis-scripts/add_required_user_and_group

before_script:
  - pip install PyYAML

script:
  - repoman full --include-dev

after_success:
  - bash <(curl --silent https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

notifications:
  email:
    on_failure: change
