dist: bionic

language: python

python:
  - pypy3

git:
  depth: 1
  quiet: true

env:
  global:
    - secure: a1vN+StnWgGSB63Vd9qoxyiqMnFSTKqYl3sBWNRCAnNi3VdR3+DdJE4jBVcoy6t82/jCnaSL3Ye1nq+t6+y0z1KifJmtqhmnP1z9MrWfKQKFwzeGKfKp4XHPcyf3x6BOPG0an/BaI/e7LjpEHIR5xD3cNuwrxVoZng4kAGLZ+RHoLge6sqxuRT6BRRxRINYSZHZEl9d5zvEKRkJhOJW3AQJ2Thj+7cnx0HpDgAc49tQVuZHHPGh3SOmZymLjhtatTO1SsqxIqxbJ7ETO+OjwghgZL7dwSR8igeKnDey5KN8op/6v3C6zax7VG+FMUqS+ojGtiDu3x0dHjiuypNpqCGaEAtrAjOp4xG0c4tY4BuYdk1CgzCRlHFSBXJ2Mx8Bv0poQuLv5Be077BsQBalyqRIcDaFluhHdvccKxpBYFOmTDCQojTvqUHf56CNCGOdp95++Gn3+SMXjNYMifHEcW/gmapjgd002lSnTk2xNv2smmGaJZsYIM1hG1zKgZwaUFuhy3JJgYiDsMDxTQ9kmB01oRs3A1lWoCf85BYGGHDIEuI6m6Rv6DfqX9U6yzBJxVmOkfcSLxZfq9vcXT8out3Bbjx1CljJnyc62WjFawOORGdeyIpr6S+ENorm/ARraU8e+08IxSBy6QNC6R2DOmuqxbGYCI9TVFhwIq8cR/WU=
    - PORTAGE_ROOT="$(mktemp --directory)"
    - PORTAGE_VERSION="$(.travis-scripts/get_latest_portage_version)"
    - PORTAGE_CONFIGROOT="${PORTAGE_ROOT}"
    - PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"
install:
  - .travis-scripts/install_portage
  - .travis-scripts/setup_portage
  - .travis-scripts/add_required_user_and_group

before_script:
  - pip install PyYAML

script:
  - repoman full --include-dev

after_success:
  - bash <(curl --silent https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

notifications:
  email:
    on_failure: change
